In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("retail_store_sales.csv")
# data
data.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [6]:
# data.info()
# data.describe()
data.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [7]:
data.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08-04-2024,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,23-07-2023,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,05-10-2022,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,07-05-2022,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,02-10-2022,False

In [8]:
data.tail()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,03-09-2023,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,12-08-2022,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,24-08-2024,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,30-12-2023,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,06-08-2022,NaN

In [10]:
data.shape

(12575, 11)

In [12]:
print(data.columns)

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='object')

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [18]:
(data.isnull().sum()/len(data)*100).round(2)

Transaction ID       0.00
Customer ID          0.00
Category             0.00
Item                 9.65
Price Per Unit       4.84
Quantity             4.80
Total Spent          4.80
Payment Method       0.00
Location             0.00
Transaction Date     0.00
Discount Applied    33.39
dtype: float64

In [19]:
data.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [20]:
(data.isnull().sum() / len(data) * 100).round(2)

Transaction ID       0.00
Customer ID          0.00
Category             0.00
Item                 9.65
Price Per Unit       4.84
Quantity             4.80
Total Spent          4.80
Payment Method       0.00
Location             0.00
Transaction Date     0.00
Discount Applied    33.39
dtype: float64

In [23]:
data["Discount Applied"] = data["Discount Applied"].fillna(0)
data.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied       0
dtype: int64

In [25]:
data[data["Discount Applied"].isnull()].head(10)
data

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08-04-2024,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,23-07-2023,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,05-10-2022,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,07-05-2022,0
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,02-10-2022,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,03-09-2023,0
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,12-08-2022,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,24-08-2024,0
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,30-12-2023,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,06-08-2022,0

In [28]:
data["Discount Applied"].value_counts(dropna=False)

Discount Applied
False    8356
True     4219
Name: count, dtype: int64

In [29]:
data["Discount Applied"].unique()

array([True, False], dtype=object)

In [31]:
data[data["Discount Applied"].isnull()][
    ["Transaction ID", "Category", "Item",
     "Price Per Unit", "Quantity", "Total Spent",
     "Discount Applied"]
].head(20)
data

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08-04-2024,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,23-07-2023,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,05-10-2022,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,07-05-2022,0
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,02-10-2022,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,03-09-2023,0
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,12-08-2022,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,24-08-2024,0
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,30-12-2023,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,06-08-2022,0

In [4]:
data["Discount Applied"].value_counts(dropna=False)

Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

In [5]:
data["Discount Applied"].value_counts(dropna=False)

data["Discount Applied"].dtype

data["Discount Applied"].unique()

array([True, False, nan], dtype=object)

In [7]:
data[data["Discount Applied"].isna()].isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                 416
Price Per Unit       205
Quantity             211
Total Spent          211
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [8]:
data[data["Discount Applied"].isna()][
    ["Item", "Price Per Unit", "Quantity", "Total Spent"]
].isnull().sum()

Item              416
Price Per Unit    205
Quantity          211
Total Spent       211
dtype: int64

In [9]:
data[data["Item"].isna()].head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,30-11-2023,NaN
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,02-04-2024,True
11,TXN_5422631,CUST_09,Milk Products,NaN,NaN,8.0,52.0,Digital Wallet,In-store,12-01-2025,True
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,11-05-2022,NaN
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,17-04-2022,NaN
19,TXN_4206593,CUST_01,Furniture,NaN,35.0,NaN,NaN,Digital Wallet,Online,13-01-2025,False
21,TXN_8685338,CUST_15,Milk Products,NaN,NaN,3.0,105.0,Credit Card,In-store,29-10-2023,NaN
25,TXN_3481599,CUST_05,Furniture,NaN,39.5,NaN,NaN,Cash,Online,08-09-2022,False
32,TXN_1543244,CUST_20,Food,NaN,NaN,8.0,196.0,Credit Card,Online,25-10-2024,True
34,TXN_1621497,CUST_06,Patisserie,NaN,23.0,NaN,NaN,Cash,In-store,18-02-2023,NaN

In [13]:
data[data["Item"].isna()][
    ["Category", "Price Per Unit", "Quantity", "Total Spent"]
].isnull().sum()

Category          0
Price Per Unit    0
Quantity          0
Total Spent       0
dtype: int64

In [11]:
data["Item"] =data["Item"].fillna("Unknow")

In [17]:
data["Item"] ="Unknow"
data

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Unknow,18.5,10.0,185.0,Digital Wallet,Online,08-04-2024,True
1,TXN_3731986,CUST_22,Milk Products,Unknow,29.0,9.0,261.0,Digital Wallet,Online,23-07-2023,True
2,TXN_9303719,CUST_02,Butchers,Unknow,21.5,2.0,43.0,Credit Card,Online,05-10-2022,False
3,TXN_9458126,CUST_06,Beverages,Unknow,27.5,9.0,247.5,Credit Card,Online,07-05-2022,NaN
4,TXN_4575373,CUST_05,Food,Unknow,12.5,7.0,87.5,Digital Wallet,Online,02-10-2022,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Unknow,38.0,4.0,152.0,Credit Card,In-store,03-09-2023,NaN
12571,TXN_4009414,CUST_03,Beverages,Unknow,6.5,9.0,58.5,Cash,Online,12-08-2022,False
12572,TXN_5306010,CUST_11,Butchers,Unknow,14.0,10.0,140.0,Cash,Online,24-08-2024,NaN
12573,TXN_5167298,CUST_04,Furniture,Unknow,14.0,6.0,84.0,Cash,Online,30-12-2023,True
12574,TXN_2407494,CUST_23,Food,Unknow,17.0,3.0,51.0,Cash,Online,06-08-2022,NaN

In [18]:
missing_summary = pd.DataFrame({
    "Missing_Count": data.isnull().sum(),
    "Missing_Percentage": (data.isnull().mean() * 100).round(2)
})

missing_summary

                  Missing_Count  Missing_Percentage
Transaction ID                0                0.00
Customer ID                   0                0.00
Category                      0                0.00
Item                          0                0.00
Price Per Unit              609                4.84
Quantity                    604                4.80
Total Spent                 604                4.80
Payment Method                0                0.00
Location                      0                0.00
Transaction Date              0                0.00
Discount Applied           4199               33.39

In [20]:
data["Calculated Total"] = data["Price Per Unit"] * data["Quantity"]

data["Calculated Total"]

0        185.0
1        261.0
2         43.0
3        247.5
4         87.5
         ...
12570    152.0
12571     58.5
12572    140.0
12573     84.0
12574     51.0
Name: Calculated Total, Length: 12575, dtype: float64

In [21]:
data[["Price Per Unit", "Quantity", "Total Spent", "Calculated Total"]].head(10)

   Price Per Unit  Quantity  Total Spent  Calculated Total
0            18.5      10.0        185.0             185.0
1            29.0       9.0        261.0             261.0
2            21.5       2.0         43.0              43.0
3            27.5       9.0        247.5             247.5
4            12.5       7.0         87.5              87.5
5             NaN      10.0        200.0               NaN
6             5.0       8.0         40.0              40.0
7            33.5       NaN          NaN               NaN
8            27.5       1.0         27.5              27.5
9            36.5       3.0        109.5             109.5

In [22]:
(
    data["Total Spent"].round(2)
    ==
    data["Calculated Total"].round(2)
).value_counts()

True     11362
False     1213
Name: count, dtype: int64

In [24]:
data[["Price Per Unit", "Quantity", "Total Spent"]].head(10)

   Price Per Unit  Quantity  Total Spent
0            18.5      10.0        185.0
1            29.0       9.0        261.0
2            21.5       2.0         43.0
3            27.5       9.0        247.5
4            12.5       7.0         87.5
5             NaN      10.0        200.0
6             5.0       8.0         40.0
7            33.5       NaN          NaN
8            27.5       1.0         27.5
9            36.5       3.0        109.5

In [27]:
data[["Price Per Unit", "Quantity", "Total Spent"]].isna().sum()

Price Per Unit    609
Quantity          604
Total Spent       604
dtype: int64

In [26]:

data[
    data["Price Per Unit"].isna() &
    data["Quantity"].notna() &
    data["Total Spent"].notna()
][["Price Per Unit", "Quantity", "Total Spent"]].head(10)

     Price Per Unit  Quantity  Total Spent
5               NaN      10.0        200.0
11              NaN       8.0         52.0
17              NaN      10.0        275.0
21              NaN       3.0        105.0
32              NaN       8.0        196.0
127             NaN      10.0        275.0
159             NaN       9.0        126.0
216             NaN       8.0         40.0
247             NaN       7.0        150.5
271             NaN       9.0         99.0

In [30]:

data.loc[
    data["Price Per Unit"].isna() &
    data["Quantity"].notna() &
    data["Total Spent"].notna(),
    "Price Per Unit"
] = (
    data["Total Spent"] / data["Quantity"]
)
data

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,Calculated Total
0,TXN_6867343,CUST_09,Patisserie,Unknow,18.5,10.0,185.0,Digital Wallet,Online,08-04-2024,True,185.0
1,TXN_3731986,CUST_22,Milk Products,Unknow,29.0,9.0,261.0,Digital Wallet,Online,23-07-2023,True,261.0
2,TXN_9303719,CUST_02,Butchers,Unknow,21.5,2.0,43.0,Credit Card,Online,05-10-2022,False,43.0
3,TXN_9458126,CUST_06,Beverages,Unknow,27.5,9.0,247.5,Credit Card,Online,07-05-2022,NaN,247.5
4,TXN_4575373,CUST_05,Food,Unknow,12.5,7.0,87.5,Digital Wallet,Online,02-10-2022,False,87.5
...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Unknow,38.0,4.0,152.0,Credit Card,In-store,03-09-2023,NaN,152.0
12571,TXN_4009414,CUST_03,Beverages,Unknow,6.5,9.0,58.5,Cash,Online,12-08-2022,False,58.5
12572,TXN_5306010,CUST_11,Butchers,Unknow,14.0,10.0,140.0,Cash,Online,24-08-2024,NaN,140.0
12573,TXN_5167298,CUST_04,Furniture,Unknow,14.0,6.0,84.0,Cash,Online,30-12-2023,True,84.0
12574,TXN_2407494,CUST_23,Food,Unknow,17.0,3.0,51.0,Cash,Online,06-08-2022,NaN,51.0

In [31]:
data["Price Per Unit"].isna().sum()

np.int64(0)